# Generated by Django 4.0.5 on 2022-07-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=245)),
                ('description', models.TextField()),
                ('rating', models.CharField(blank=True, max_length=55, null=True)),
                ('image', models.ImageField(upload_to='course/')),
                ('author', models.CharField(max_length=55)),
                ('duration', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
