# Generated by Django 4.0.5 on 2022-07-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecategory_feedback_tag_remove_lesson__in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
