# Generated by Django 4.0.5 on 2022-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]
    #
    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INSTRUCTOR', 'instructor'), ('STUDENT', 'student')], default='', max_length=18),
            preserve_default=False,
        ),
    ]
